backend/task_platform/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :task_sets_users
  resources :task_results
  resources :classification_options
  resources :data_points_task_sets
  resources :task_sets
  resources :tasks
  resources :alien_comments
  resources :alien_stories
  resources :data_points
  resources :datasets
  resources :user

  namespace :api do
    namespace :v1 do
      resources :sessions, only: :create
      resources :alien_stories, only: :index
      resource :next_alien_comment, only: :show
      resource :next_data_point, only: :show
      resource :random_task_set, only: :show
      resources :task_results, only: :create
      resources :tasks, only: :index
      resources :users, only: [:index, :create]
      resources :batch_task_results, only: :create
      resources :unfinished_data_points, only: :index
    end
  end

  root to: "home#index"
end

backend/task_platform/app/models/classification_option.rb
# == Schema Information
#
# Table name: classification_options
#
#  id         :bigint           not null, primary key
#  name       :string
#  task_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class ClassificationOption < ApplicationRecord
  belongs_to :task
end

backend/task_platform/app/controllers/classification_options_controller.rb
class ClassificationOptionsController < ApplicationController
  before_action :set_classification_option, only: %i[ show edit update destroy ]

  # GET /classification_options or /classification_options.json
  def index
    @classification_options = ClassificationOption.all
  end

  # GET /classification_options/1 or /classification_options/1.json
  def show
  end

  # GET /classification_options/new
  def new
    @classification_option = ClassificationOption.new
  end

  # GET /classification_options/1/edit
  def edit
  end

  # POST /classification_options or /classification_options.json
  def create
    @classification_option = ClassificationOption.new(classification_option_params)

    respond_to do |format|
      if @classification_option.save
        format.html { redirect_to classification_option_url(@classification_option), notice: "Classification option was successfully created." }
        format.json { render :show, status: :created, location: @classification_option }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @classification_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classification_options/1 or /classification_options/1.json
  def update
    respond_to do |format|
      if @classification_option.update(classification_option_params)
        format.html { redirect_to classification_option_url(@classification_option), notice: "Classification option was successfully updated." }
        format.json { render :show, status: :ok, location: @classification_option }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @classification_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classification_options/1 or /classification_options/1.json
  def destroy
    @classification_option.destroy

    respond_to do |format|
      format.html { redirect_to classification_options_url, notice: "Classification option was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classification_option
      @classification_option = ClassificationOption.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def classification_option_params
      params.require(:classification_option).permit(:name, :task_id)
    end
end

backend/task_platform/app/helpers/classification_options_helper.rb
module ClassificationOptionsHelper
end

backend/task_platform/app/views/classification_options/_form.html.erb
<%= form_with(model: classification_option) do |form| %>
  <% if classification_option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(classification_option.errors.count, "error") %> prohibited this classification_option from being saved:</h2>

      <ul>
        <% classification_option.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :task_id %>
    <%= form.collection_select :task_id, Task.all, :id, :representable_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/task_platform/app/views/classification_options/edit.html.erb
<h1>Editing Classification Option</h1>

<%= render 'form', classification_option: @classification_option %>

<%= link_to 'Show', @classification_option %> |
<%= link_to 'Back', classification_options_path %>

backend/task_platform/app/views/classification_options/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Classification Options</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dataset</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classification_options.each do |classification_option| %>
      <tr>
        <td><%= classification_option.name %></td>
        <td><%= classification_option.task.representable_name %></td>
        <td><%= link_to 'Show', classification_option %></td>
        <td><%= link_to 'Edit', edit_classification_option_path(classification_option) %></td>
        <td><%= link_to 'Destroy', classification_option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Classification Option', new_classification_option_path %>

backend/task_platform/app/views/classification_options/new.html.erb
<h1>New Classification Option</h1>

<%= render 'form', classification_option: @classification_option %>

<%= link_to 'Back', classification_options_path %>

backend/task_platform/app/views/classification_options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @classification_option.name %>
</p>

<p>
  <strong>Dataset:</strong>
  <%= @classification_option.task.representable_name %>
</p>

<%= link_to 'Edit', edit_classification_option_path(@classification_option) %> |
<%= link_to 'Back', classification_options_path %>