backend/task_platform/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :task_sets_users
  resources :task_results
  resources :classification_options
  resources :data_points_task_sets
  resources :task_sets
  resources :tasks
  resources :alien_comments
  resources :alien_stories
  resources :data_points
  resources :datasets
  resources :user

  namespace :api do
    namespace :v1 do
      resources :sessions, only: :create
      resources :alien_stories, only: :index
      resource :next_alien_comment, only: :show
      resource :next_data_point, only: :show
      resource :random_task_set, only: :show
      resources :task_results, only: :create
      resources :tasks, only: :index
      resources :users, only: [:index, :create]
      resources :batch_task_results, only: :create
      resources :unfinished_data_points, only: :index
    end
  end

  root to: "home#index"
end

backend/task_platform/app/models/task_result.rb
# == Schema Information
#
# Table name: task_results
#
#  id                    :bigint           not null, primary key
#  user_id               :bigint           not null
#  data_point_id         :bigint           not null
#  task_set_id           :bigint           not null
#  classification        :string
#  masked_words          :string           is an Array
#  rationale_words       :string           is an Array
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  rationale_words2      :string           is an Array
#  free_text_explanation :string
#
class TaskResult < ApplicationRecord
  belongs_to :user
  belongs_to :data_point
  belongs_to :task_set
end

backend/task_platform/app/controllers/api/v1/task_results_controller.rb
class Api::V1::TaskResultsController < Api::V1::ApplicationController
  # Input:
  # - task_set_id
  # - data_point_id
  # - classification
  # - rationale_words
  # - rationale_words2 (only for multi input tasks)
  # - free_text_explanation (optional)
  #
  # Output:
  # - next data_point
  def create
    @task_result = current_user.task_results.new(task_result_params)

    if @task_result.save
      # task_set = TaskSet.find_by(id: params[:task_set_id])
      
      # if task_set.present? && task_set.data_points.unfinished_for_user(current_user, task_set).blank?
      #   task_sets_user = task_set.task_sets_users.find_by(user: current_user)
      #   task_sets_user&.update!(finished: true)
      # end

      current_user.assign_to_task_sets
      current_user.set_task_sets_users_finished

      render json: { success: true }, status: :ok
    else
      render json: { errors: @task_result.errors.full_messages }, status: :unprocessable_entity
    end
  end

  protected

  def task_result_params
    params.permit(
      :task_set_id,
      :data_point_id,
      :classification,
      :free_text_explanation,
      rationale_words: [],
      rationale_words2: []
    )
  end
end

backend/task_platform/app/controllers/task_results_controller.rb
class TaskResultsController < ApplicationController
  before_action :set_task_result, only: %i[ show edit update destroy ]

  # GET /task_results or /task_results.json
  def index
    @task_results = TaskResult.all
  end

  # GET /task_results/1 or /task_results/1.json
  def show
  end

  # GET /task_results/new
  def new
    @task_result = TaskResult.new
  end

  # GET /task_results/1/edit
  def edit
  end

  # POST /task_results or /task_results.json
  def create
    @task_result = TaskResult.new(task_result_params)

    respond_to do |format|
      if @task_result.save
        format.html { redirect_to task_result_url(@task_result), notice: "Task result was successfully created." }
        format.json { render :show, status: :created, location: @task_result }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_results/1 or /task_results/1.json
  def update
    respond_to do |format|
      if @task_result.update(task_result_params)
        format.html { redirect_to task_result_url(@task_result), notice: "Task result was successfully updated." }
        format.json { render :show, status: :ok, location: @task_result }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_results/1 or /task_results/1.json
  def destroy
    @task_result.destroy

    respond_to do |format|
      format.html { redirect_to task_results_url, notice: "Task result was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_result
      @task_result = TaskResult.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_result_params
      params.require(:task_result).permit(:user_id, :data_point_id, :task_set_id, :classification, :masked_words, :rationale_words)
    end
end

backend/task_platform/app/helpers/task_results_helper.rb
module TaskResultsHelper
end

backend/task_platform/app/views/task_results/_form.html.erb
<%= form_with(model: task_result) do |form| %>
  <% if task_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task_result.errors.count, "error") %> prohibited this task_result from being saved:</h2>

      <ul>
        <% task_result.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :data_point_id %>
    <%= form.collection_select :data_point_id, DataPoint.all, :id, :representable_name %>
  </div>

  <div class="field">
    <%= form.label :task_set_id %>
    <%= form.collection_select :task_set_id, TaskSet.all, :id, :representable_name %>
  </div>

  <div class="field">
    <%= form.label :classification %>
    <%= form.text_field :classification %>
  </div>

  <div class="field">
    <%= form.label :masked_words %>
    <%= form.text_field :masked_words %>
  </div>

  <div class="field">
    <%= form.label :rationale_words %>
    <%= form.text_field :rationale_words %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/task_platform/app/views/task_results/edit.html.erb
<h1>Editing Task Result</h1>

<%= render 'form', task_result: @task_result %>

<%= link_to 'Show', @task_result %> |
<%= link_to 'Back', task_results_path %>

backend/task_platform/app/views/task_results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Task Results</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Data point</th>
      <th>Task set</th>
      <th>Classification</th>
      <th>Masked words</th>
      <th>Rationale words</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_results.each do |task_result| %>
      <tr>
        <td><%= task_result.user_id %></td>
        <td><%= task_result.data_point.representable_name %></td>
        <td><%= task_result.task_set.representable_name %></td>
        <td><%= task_result.classification %></td>
        <td><%= task_result.masked_words %></td>
        <td><%= task_result.rationale_words %></td>
        <td><%= link_to 'Show', task_result %></td>
        <td><%= link_to 'Edit', edit_task_result_path(task_result) %></td>
        <td><%= link_to 'Destroy', task_result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task Result', new_task_result_path %>

backend/task_platform/app/views/task_results/new.html.erb
<h1>New Task Result</h1>

<%= render 'form', task_result: @task_result %>

<%= link_to 'Back', task_results_path %>

backend/task_platform/app/views/task_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @task_result.user_id %>
</p>

<p>
  <strong>Data point:</strong>
  <%= @task_result.data_point.representable_name %>
</p>

<p>
  <strong>Task set:</strong>
  <%= @task_result.task_set.representable_name %>
</p>

<p>
  <strong>Classification:</strong>
  <%= @task_result.classification %>
</p>

<p>
  <strong>Masked words:</strong>
  <%= @task_result.masked_words %>
</p>

<p>
  <strong>Rationale words:</strong>
  <%= @task_result.rationale_words %>
</p>

<%= link_to 'Edit', edit_task_result_path(@task_result) %> |
<%= link_to 'Back', task_results_path %>