backend/task_platform/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :task_sets_users
  resources :task_results
  resources :classification_options
  resources :data_points_task_sets
  resources :task_sets
  resources :tasks
  resources :alien_comments
  resources :alien_stories
  resources :data_points
  resources :datasets
  resources :user

  namespace :api do
    namespace :v1 do
      resources :sessions, only: :create
      resources :alien_stories, only: :index
      resource :next_alien_comment, only: :show
      resource :next_data_point, only: :show
      resource :random_task_set, only: :show
      resources :task_results, only: :create
      resources :tasks, only: :index
      resources :users, only: [:index, :create]
      resources :batch_task_results, only: :create
      resources :unfinished_data_points, only: :index
    end
  end

  root to: "home#index"
end

backend/task_platform/app/models/dataset.rb
# == Schema Information
#
# Table name: datasets
#
#  id            :bigint           not null, primary key
#  name          :string
#  gold_standard :boolean          default(FALSE), not null
#  task_id       :bigint           not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Dataset < ApplicationRecord
  belongs_to :task

  has_many :data_points, dependent: :destroy
end

backend/task_platform/app/controllers/datasets_controller.rb
class DatasetsController < ApplicationController
  before_action :set_dataset, only: %i[ show edit update destroy ]

  # GET /datasets or /datasets.json
  def index
    @datasets = Dataset.all
  end

  # GET /datasets/1 or /datasets/1.json
  def show
  end

  # GET /datasets/new
  def new
    @dataset = Dataset.new
  end

  # GET /datasets/1/edit
  def edit
  end

  # POST /datasets or /datasets.json
  def create
    @dataset = Dataset.new(dataset_params)

    respond_to do |format|
      if @dataset.save
        format.html { redirect_to dataset_url(@dataset), notice: "Dataset was successfully created." }
        format.json { render :show, status: :created, location: @dataset }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dataset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /datasets/1 or /datasets/1.json
  def update
    respond_to do |format|
      if @dataset.update(dataset_params)
        format.html { redirect_to dataset_url(@dataset), notice: "Dataset was successfully updated." }
        format.json { render :show, status: :ok, location: @dataset }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dataset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datasets/1 or /datasets/1.json
  def destroy
    @dataset.destroy

    respond_to do |format|
      format.html { redirect_to datasets_url, notice: "Dataset was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dataset
      @dataset = Dataset.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dataset_params
      params.require(:dataset).permit(:name, :task_id)
    end
end

backend/task_platform/app/helpers/datasets_helper.rb
module DatasetsHelper
end

backend/task_platform/app/views/datasets/_form.html.erb
<%= form_with(model: dataset) do |form| %>
  <% if dataset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dataset.errors.count, "error") %> prohibited this dataset from being saved:</h2>

      <ul>
        <% dataset.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :task_id %>
    <%= form.collection_select :task_id, Task.all, :id, :representable_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/task_platform/app/views/datasets/edit.html.erb
<h1>Editing Dataset</h1>

<%= render 'form', dataset: @dataset %>

<%= link_to 'Show', @dataset %> |
<%= link_to 'Back', datasets_path %>

backend/task_platform/app/views/datasets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Datasets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Task</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @datasets.each do |dataset| %>
      <tr>
        <td><%= dataset.name %></td>
        <td><%= dataset.task.representable_name %></td>
        <td><%= link_to 'Show', dataset %></td>
        <td><%= link_to 'Edit', edit_dataset_path(dataset) %></td>
        <td><%= link_to 'Destroy', dataset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dataset', new_dataset_path %>

backend/task_platform/app/views/datasets/new.html.erb
<h1>New Dataset</h1>

<%= render 'form', dataset: @dataset %>

<%= link_to 'Back', datasets_path %>

backend/task_platform/app/views/datasets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dataset.name %>
</p>

<p>
  <strong>Task:</strong>
  <%= @dataset.task.representable_name %>
</p>

<%= link_to 'Edit', edit_dataset_path(@dataset) %> |
<%= link_to 'Back', datasets_path %>