backend/task_platform/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :task_sets_users
  resources :task_results
  resources :classification_options
  resources :data_points_task_sets
  resources :task_sets
  resources :tasks
  resources :alien_comments
  resources :alien_stories
  resources :data_points
  resources :datasets
  resources :user

  namespace :api do
    namespace :v1 do
      resources :sessions, only: :create
      resources :alien_stories, only: :index
      resource :next_alien_comment, only: :show
      resource :next_data_point, only: :show
      resource :random_task_set, only: :show
      resources :task_results, only: :create
      resources :tasks, only: :index
      resources :users, only: [:index, :create]
      resources :batch_task_results, only: :create
      resources :unfinished_data_points, only: :index
    end
  end

  root to: "home#index"
end

backend/task_platform/app/models/data_point.rb
# == Schema Information
#
# Table name: data_points
#
#  id                    :bigint           not null, primary key
#  input                 :text
#  input2                :text
#  maskable_words        :string           is an Array
#  custom_options        :string           is an Array
#  dataset_id            :bigint           not null
#  classification        :string
#  rationale_words       :string           is an Array
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  rationale_words2      :string           is an Array
#  free_text_explanation :string
#
class DataPoint < ApplicationRecord
  self.implicit_order_column = "input"
  belongs_to :dataset

  has_many :data_points_task_sets, dependent: :destroy
  has_many :task_sets, through: :data_points_task_sets

  has_many :task_results, dependent: :destroy

  scope :unfinished_for_user, ->(user, task_set){
    joins(:task_sets).left_outer_joins(:task_results)
        .preload(:task_sets, :task_results)
        .where(task_sets: { id: task_set.id })
        .group('data_points.id')
        .having(Arel.sql("COUNT((CASE WHEN task_results.user_id = #{user.id} AND task_results.task_set_id = #{task_set.id} THEN 1 END)) = 0"))
        .select('data_points.*')
  }

  scope :finished_for_user, ->(user, task_set){
    joins(:task_sets).joins(:task_results)
        .preload(:task_sets, :task_results)
        .where(task_sets: { id: task_set.id })
        .group('data_points.id')
        .having(Arel.sql("COUNT((CASE WHEN task_results.user_id = #{user.id} AND task_results.task_set_id = #{task_set.id} THEN 1 END)) > 0"))
        .select('data_points.*')
  }

  scope :by_task_set_order, ->{
    left_outer_joins(:data_points_task_sets)
        .preload(:data_points_task_sets)
        .order('data_points_task_sets.id')
  }

  scope :by_usage, ->{
    left_outer_joins(:task_sets)
        .preload(:task_sets)
        .group('data_points.id')
        .order('COUNT(task_sets.id)')
        .random
        .select('data_points.*')
  }

  scope :random, ->(seed = rand(0.0..10.0)){
    pg_seed = seed.to_f / (seed.abs + 1)
    DataPoint.connection.execute("select setseed(#{pg_seed})")

    order('RANDOM()')
  }

  scope :with_classification, ->{
    where.not(classification: nil)
  }

  scope :without_classification, ->{
    where(classification: nil)
  }

  scope :with_rationale_words, ->{
    where.not(rationale_words: nil)
        .where.not(rationale_words: [])
  }

  scope :with_rationale_words2, ->{
    where.not(rationale_words2: nil)
        .where.not(rationale_words2: [])
  }

  scope :gold_standard, ->{
    with_classification
        .with_rationale_words
        .with_rationale_words2
  }
end

backend/task_platform/app/controllers/data_points_controller.rb
class DataPointsController < ApplicationController
  before_action :set_data_point, only: %i[ show edit update destroy ]

  # GET /data_points or /data_points.json
  def index
    @data_points = DataPoint.all
  end

  # GET /data_points/1 or /data_points/1.json
  def show
  end

  # GET /data_points/new
  def new
    @data_point = DataPoint.new
  end

  # GET /data_points/1/edit
  def edit
  end

  # POST /data_points or /data_points.json
  def create
    @data_point = DataPoint.new(data_point_params)

    respond_to do |format|
      if @data_point.save
        format.html { redirect_to data_point_url(@data_point), notice: "Data point was successfully created." }
        format.json { render :show, status: :created, location: @data_point }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @data_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /data_points/1 or /data_points/1.json
  def update
    respond_to do |format|
      if @data_point.update(data_point_params)
        format.html { redirect_to data_point_url(@data_point), notice: "Data point was successfully updated." }
        format.json { render :show, status: :ok, location: @data_point }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @data_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /data_points/1 or /data_points/1.json
  def destroy
    @data_point.destroy

    respond_to do |format|
      format.html { redirect_to data_points_url, notice: "Data point was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_data_point
      @data_point = DataPoint.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def data_point_params
      params.require(:data_point).permit(:input, :input2, :maskable_words, :custom_options, :dataset_id, :classification, :rationale_words)
    end
end

backend/task_platform/app/helpers/data_points_helper.rb
module DataPointsHelper
end

backend/task_platform/app/views/data_points/_form.html.erb
<%= form_with(model: data_point) do |form| %>
  <% if data_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(data_point.errors.count, "error") %> prohibited this data_point from being saved:</h2>

      <ul>
        <% data_point.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :input %>
    <%= form.text_area :input %>
  </div>

  <div class="field">
    <%= form.label :input2 %>
    <%= form.text_area :input2 %>
  </div>

  <div class="field">
    <%= form.label :maskable_words %>
    <%= form.text_field :maskable_words %>
  </div>

  <div class="field">
    <%= form.label :custom_options %>
    <%= form.text_field :custom_options %>
  </div>

  <div class="field">
    <%= form.label :dataset_id %>
    <%= form.collection_select :dataset_id, Dataset.all, :id, :representable_name %>
  </div>

  <div class="field">
    <%= form.label :classification %>
    <%= form.text_field :classification %>
  </div>

  <div class="field">
    <%= form.label :rationale_words %>
    <%= form.text_field :rationale_words %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/task_platform/app/views/data_points/edit.html.erb
<h1>Editing Data Point</h1>

<%= render 'form', data_point: @data_point %>

<%= link_to 'Show', @data_point %> |
<%= link_to 'Back', data_points_path %>

backend/task_platform/app/views/data_points/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Data Points</h1>

<table>
  <thead>
    <tr>
      <th>Input</th>
      <th>Input2</th>
      <th>Maskable words</th>
      <th>Custom options</th>
      <th>Dataset</th>
      <th>Classification</th>
      <th>Rationale words</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @data_points.each do |data_point| %>
      <tr>
        <td><%= data_point.input %></td>
        <td><%= data_point.input2 %></td>
        <td><%= data_point.maskable_words %></td>
        <td><%= data_point.custom_options %></td>
        <td><%= data_point.dataset.representable_name %></td>
        <td><%= data_point.classification %></td>
        <td><%= data_point.rationale_words %></td>
        <td><%= link_to 'Show', data_point %></td>
        <td><%= link_to 'Edit', edit_data_point_path(data_point) %></td>
        <td><%= link_to 'Destroy', data_point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Data Point', new_data_point_path %>

backend/task_platform/app/views/data_points/new.html.erb
<h1>New Data Point</h1>

<%= render 'form', data_point: @data_point %>

<%= link_to 'Back', data_points_path %>

backend/task_platform/app/views/data_points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Input:</strong>
  <%= @data_point.input %>
</p>

<p>
  <strong>Input2:</strong>
  <%= @data_point.input2 %>
</p>

<p>
  <strong>Maskable words:</strong>
  <%= @data_point.maskable_words %>
</p>

<p>
  <strong>Custom options:</strong>
  <%= @data_point.custom_options %>
</p>

<p>
  <strong>Dataset:</strong>
  <%= @data_point.dataset.representable_name %>
</p>

<p>
  <strong>Classification:</strong>
  <%= @data_point.classification %>
</p>

<p>
  <strong>Rationale words:</strong>
  <%= @data_point.rationale_words %>
</p>

<%= link_to 'Edit', edit_data_point_path(@data_point) %> |
<%= link_to 'Back', data_points_path %>